import type { Metadata } from "next";

import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

import { helvetica, helveticaNeue, openSans, sora } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={[sora.variable, openSans.variable, helvetica.variable, helveticaNeue.variable].join(" ")}
    >
      <body className={`font-open antialiased`}>{children}</body>
    </html>
  );
}
